import Link from 'next/link'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">
            Home
          </Link>
          <Link href="/notes">
            Notes
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
